=== alllucky1996/SmartERP/src/Smartstore.Modules/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Schema for module JSON file format",
  "type": "object",
  "required": [ "FriendlyName", "SystemName", "Version" ],
  "properties": {
    "FriendlyName": {
      "type": "string",
      "description": "English (unlocalized) friendly name."
    },
    "Description": {
      "type": "string",
      "description": "English (unlocalized) description."
    },
    "SystemName": {
      "type": "string",
      "description": "Module system name (usually the assembly name without extension)."
    },
    "Author": {
      "type": "string",
      "description": "Author name."
    },
    "ProjectUrl": {
      "type": "string",
      "description": "Link to project's or author's homepage."
    },
    "Tags": {
      "type": "string",
      "description": "Comma-separated tags."
    },
    "Version": {
      "type": "string",
      "description": "The current version of module, e.g. '2.1.0'."
    },
    "MinAppVersion": {
      "type": "string",
      "description": "The minimum compatible application version, e.g. '5.0.0'."
    },
    "ResourceRootKey": {
      "type": "string",
      "description": "Root key for language resources."
    },
    "AssemblyName": {
      "type": "string",
      "description": "Optional assembly name. By default '{SystemName}.dll' is assumed to be the assembly name."
    },
    "Order": {
      "type": "integer",
      "description": "The display order in the module manager group."
    },
    "PrivateReferences": {
      "type": "array",
      "description": "Optional array of private dependency package names that this module references. By default, referenced packages are not copied to the module's output directory because it is assumed that the application core references them already. Any module private package should be listed here (including the complete dependency chain).",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "DependsOn": {
      "type": "array",
      "description": "Optional array of module system names that this module depends on.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "Group": {
      "description": "Conceptual group name. Used to visually categorize module in module listings.",
      "enum": [
        "Admin",
        "Marketing",
        "Payment",
        "Shipping",
        "Tax",
        "Analytics",
        "CMS",
        "Media",
        "SEO",
        "Data",
        "Globalization",
        "Api",
        "Mobile",
        "Social",
        "Security",
        "Developer",
        "Sales",
        "Design",
        "Performance",
        "B2B",
        "Storefront",
        "Law"
      ]
    }
  }
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Google.MerchantCenter/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Marketing",
  "SystemName": "Smartstore.Google.MerchantCenter",
  "FriendlyName": "Google Merchant Center (GMC) feed",
  "Description": "Exports products in the Google Merchant Center feed format.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Feed.Froogle",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/37-google-merchant-center-gmc-feed/"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Facebook.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Facebook.Auth",
  "FriendlyName": "Facebook Authentication",
  "Description": "Enables login with Facebook account.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.ExternalAuth.Facebook",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Facebook"
  ]
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Twitter.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Twitter.Auth",
  "FriendlyName": "Twitter Authentication",
  "Description": "Enables login with Twitter account.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.ExternalAuth.Twitter",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Twitter"
  ]
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.AmazonPay/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Payment",
  "SystemName": "Smartstore.AmazonPay",
  "FriendlyName": "Amazon Pay",
  "Description": "Login and Pay with Amazon",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Payments.AmazonPay",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/11-amazon-payments-plugin/",
  "PrivateReferences": ["Amazon.Pay.API.SDK"]
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Google.Analytics/module.json
{
  "$schema": "../module.schema.json",
  "Author": "Smartstore AG",
  "Group": "Analytics",
  "SystemName": "Smartstore.Google.Analytics",
  "FriendlyName": "Google Analytics",
  "Description": "Adds Google Analytics tracking scripts to the shop",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Widgets.GoogleAnalytics",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/25-google-analytics/"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Google.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Google.Auth",
  "FriendlyName": "Google Authentication",
  "Description": "Enables login with Google account.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.Google.Auth",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.Google"
  ]
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.DevTools/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Developer",
  "SystemName": "Smartstore.DevTools",
  "FriendlyName": "Smartstore Developer Tools (MiniProfiler and other goodies)",
  "Description": "",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Developer.DevTools",
  "PrivateReferences": [
    "MiniProfiler.Shared",
    "MiniProfiler.AspNetCore",
    "MiniProfiler.AspNetCore.Mvc",
    "MiniProfiler.EntityFrameworkCore"
  ]
}
