=== alllucky1996/SmartERP/src/Smartstore.Modules/module.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Schema for module JSON file format",
  "type": "object",
  "required": [ "FriendlyName", "SystemName", "Version" ],
  "properties": {
    "FriendlyName": {
      "type": "string",
      "description": "English (unlocalized) friendly name."
    },
    "Description": {
      "type": "string",
      "description": "English (unlocalized) description."
    },
    "SystemName": {
      "type": "string",
      "description": "Module system name (usually the assembly name without extension)."
    },
    "Author": {
      "type": "string",
      "description": "Author name."
    },
    "ProjectUrl": {
      "type": "string",
      "description": "Link to project's or author's homepage."
    },
    "Tags": {
      "type": "string",
      "description": "Comma-separated tags."
    },
    "Version": {
      "type": "string",
      "description": "The current version of module, e.g. '2.1.0'."
    },
    "MinAppVersion": {
      "type": "string",
      "description": "The minimum compatible application version, e.g. '5.0.0'."
    },
    "ResourceRootKey": {
      "type": "string",
      "description": "Root key for language resources."
    },
    "AssemblyName": {
      "type": "string",
      "description": "Optional assembly name. By default '{SystemName}.dll' is assumed to be the assembly name."
    },
    "Order": {
      "type": "integer",
      "description": "The display order in the module manager group."
    },
    "PrivateReferences": {
      "type": "array",
      "description": "Optional array of private dependency package names that this module references. By default, referenced packages are not copied to the module's output directory because it is assumed that the application core references them already. Any module private package should be listed here (including the complete dependency chain).",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "DependsOn": {
      "type": "array",
      "description": "Optional array of module system names that this module depends on.",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "Group": {
      "description": "Conceptual group name. Used to visually categorize module in module listings.",
      "enum": [
        "Admin",
        "Marketing",
        "Payment",
        "Shipping",
        "Tax",
        "Analytics",
        "CMS",
        "Media",
        "SEO",
        "Data",
        "Globalization",
        "Api",
        "Mobile",
        "Social",
        "Security",
        "Developer",
        "Sales",
        "Design",
        "Performance",
        "B2B",
        "Storefront",
        "Law"
      ]
    }
  }
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.PayPal/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Payment",
  "SystemName": "Smartstore.PayPal",
  "FriendlyName": "Smartstore.PayPal",
  "Description": "Enables payments with PayPal",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.PayPal",
  "ProjectUrl": "http://community.smartstore.com/marketplace/file/29-paypal-payment-plugins/"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.ShippingByWeight/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Shipping",
  "SystemName": "Smartstore.ShippingByWeight",
  "FriendlyName": "Shipping by weight",
  "Description": "Provides shipping methods with computation based on weight.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Shipping.ByWeight",
  "ProjectUrl": ""
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Microsoft.Auth/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Security",
  "SystemName": "Smartstore.Microsoft.Auth",
  "FriendlyName": "Microsoft Authentication",
  "Description": "Enables login with Microsoft account.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.Microsoft.Auth",
  "PrivateReferences": [
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount"
  ]
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Tax/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Tax",
  "SystemName": "Smartstore.Tax",
  "FriendlyName": "Default Tax Providers",
  "Description": "Contains default tax providers like FixedRate & ByRegion",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 0,
  "ResourceRootKey": "Plugins.SmartStore.Tax"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Clickatell/module.json
{
  "$schema": "../module.schema.json",
  "Author": "SmartStore AG",
  "Group": "Mobile",
  "SystemName": "Smartstore.Clickatell",
  "FriendlyName": "Clickatell SMS Provider",
  "Description": "Sends order notifications to shop administrator via SMS",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Order": 1,
  "ResourceRootKey": "Plugins.Sms.Clickatell"
}

=== alllucky1996/SmartERP/src/alllucky1996/Smartstore_modules/src/Smartstore.Web/Modules/Smartstore.PriceBuilder/module.json
{
  "$schema": "../module.schema.json",
  "Group": "CMS",
  "SystemName": "Smartstore.PriceBuilder",
  "FriendlyName": "Smartstore Price Builder",
  "Description": "Synthesize and calculate prices of product from many influencing factors",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "Nguyễn Anh Dũng",
  "Order": 1,
  "ResourceRootKey": "Plugins.CMS.Blog"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.OfflinePayment/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Payment",
  "SystemName": "Smartstore.OfflinePayment",
  "FriendlyName": "Adds offline payment methods to the store",
  "Description": "",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 1,
  "ResourceRootKey": "Plugins.Smartstore.OfflinePayment"
}

=== alllucky1996/SmartERP/src/Smartstore.Modules/Smartstore.Shipping/module.json
{
  "$schema": "../module.schema.json",
  "Group": "Shipping",
  "SystemName": "Smartstore.Shipping",
  "FriendlyName": "Default Shipping Providers",
  "Description": "Provides shipping methods for fixed rate shipping and computation based on total.",
  "Version": "5.0",
  "MinAppVersion": "5.0",
  "Author": "SmartStore AG",
  "Order": 0,
  "ResourceRootKey": "Plugins.SmartStore.Shipping"
}
